<?php
/**
 * Reading Mode Controls Template
 *
 * This template is used by JavaScript to render the reading mode controls panel.
 * It's kept as a separate template for easier maintenance and customization.
 *
 * Note: This template is not directly included in PHP. It serves as a reference
 * for the HTML structure generated by reading-mode.js
 *
 * @package SagaManagerTheme
 * @since 1.0.0
 */

declare(strict_types=1);

// Prevent direct access
if (!defined('ABSPATH')) {
    exit;
}

/**
 * This template is for reference only.
 * The actual controls are generated dynamically by JavaScript
 * in assets/js/reading-mode.js for better performance and flexibility.
 *
 * You can customize the controls by modifying the createControls() method
 * in the ReadingModeManager class.
 */
?>

<!-- Reading Mode Controls Structure (Reference) -->
<!--
<div class="reading-mode-controls" aria-label="Reading Mode Controls">
    <div class="reading-mode-controls__container">

        // Exit Button
        <button class="rm-exit" aria-label="Exit reading mode (Esc)" title="Exit (Esc)">
            ×
        </button>

        <div class="rm-settings">

            // Font Size Controls
            <div class="rm-setting-group rm-font-size">
                <span class="rm-setting-label">Font Size</span>
                <button data-size="small" aria-label="Small font" title="Small (-)">A</button>
                <button data-size="medium" aria-label="Medium font" title="Medium">A</button>
                <button data-size="large" aria-label="Large font" title="Large (+)">A</button>
                <button data-size="xlarge" aria-label="Extra large font" title="Extra Large">A</button>
            </div>

            // Line Height Controls
            <div class="rm-setting-group rm-line-height">
                <span class="rm-setting-label">Spacing</span>
                <button data-spacing="compact" aria-label="Compact spacing" title="Compact">☰</button>
                <button data-spacing="normal" aria-label="Normal spacing" title="Normal">☰</button>
                <button data-spacing="relaxed" aria-label="Relaxed spacing" title="Relaxed">☰</button>
            </div>

            // Theme Controls
            <div class="rm-setting-group rm-theme">
                <span class="rm-setting-label">Theme</span>
                <button data-theme="light" aria-label="Light theme" title="Light (1)">☀️</button>
                <button data-theme="sepia" aria-label="Sepia theme" title="Sepia (2)">📄</button>
                <button data-theme="dark" aria-label="Dark theme" title="Dark (3)">🌙</button>
                <button data-theme="black" aria-label="Black theme" title="Black (4)">⬛</button>
            </div>

        </div>
    </div>

    // Progress Bar
    <div class="rm-progress-bar" role="progressbar" aria-label="Reading progress" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0">
        <div class="rm-progress-fill"></div>
    </div>
</div>
-->

<?php
/**
 * Customization Guide:
 *
 * To customize the controls panel:
 *
 * 1. Modify the createControls() method in assets/js/reading-mode.js
 * 2. Update corresponding CSS in assets/css/reading-mode.css
 * 3. Use WordPress filters to modify behavior:
 *
 * Example filters:
 *
 * // Disable auto-hide controls
 * add_filter('saga_reading_mode_auto_hide', '__return_false');
 *
 * // Change default theme
 * add_filter('saga_reading_mode_default_theme', function() {
 *     return 'dark';
 * });
 *
 * // Customize available font sizes
 * add_filter('saga_reading_mode_font_sizes', function($sizes) {
 *     return ['small', 'medium', 'large']; // Remove xlarge
 * });
 *
 * // Add custom theme
 * add_filter('saga_reading_mode_themes', function($themes) {
 *     $themes['custom'] = [
 *         'name' => 'Custom',
 *         'background' => '#f0f0f0',
 *         'color' => '#333333',
 *     ];
 *     return $themes;
 * });
 */
?>

<?php
/**
 * Keyboard Shortcuts Reference:
 *
 * Esc          - Exit reading mode
 * + or =       - Increase font size
 * -            - Decrease font size
 * 1            - Light theme
 * 2            - Sepia theme
 * 3            - Dark theme
 * 4            - Black theme
 * Space        - Toggle controls panel (when focused on container)
 */
?>

<?php
/**
 * Accessibility Features:
 *
 * - ARIA labels on all interactive elements
 * - Role="dialog" on reading mode container
 * - Role="progressbar" on progress indicator
 * - Focus trap within reading mode
 * - Screen reader announcements for setting changes
 * - High contrast mode support
 * - Reduced motion support
 * - Keyboard navigation
 * - Touch-friendly controls on mobile
 */
?>

<?php
/**
 * Mobile Optimizations:
 *
 * - Touch-friendly button sizes (minimum 44x44px)
 * - Responsive layout for controls
 * - Simplified controls on small screens
 * - Full-width reading area
 * - Optimized font sizes for mobile
 * - Bottom sheet controls option (via CSS)
 */
?>

<?php
/**
 * Print Support:
 *
 * - Controls hidden when printing
 * - Clean, optimized print layout
 * - Black text on white background
 * - Remove unnecessary decorations
 * - Page break optimization
 */
?>

<?php
/**
 * Performance Considerations:
 *
 * - Controls generated dynamically (not server-rendered)
 * - Minimal DOM manipulation
 * - Smooth CSS transitions
 * - Efficient scroll handling with RAF
 * - LocalStorage for preferences (no server requests)
 * - Lazy-loaded (only when entering reading mode)
 */
?>

<?php
/**
 * Browser Compatibility:
 *
 * - Modern browsers (Chrome, Firefox, Safari, Edge)
 * - Graceful degradation for older browsers
 * - Polyfills not required (vanilla JS)
 * - CSS custom properties with fallbacks
 * - Backdrop-filter with fallback
 */
?>
